version: '3.4'
volumes:
    slave-m2-repository:
    gerrit:
    jenkins:
    nexus:
    ldap_data:
    ldap_config:
services:
    ldap:
        image: osixia/openldap:1.2.4
        environment:
            LDAP_ORGANISATION: ${LDAP_ORGANISATION:-My Company}
            LDAP_DOMAIN: ${LDAP_DOMAIN:-example.org}
            LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin123}
        command: --copy-service
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
            - ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif
    ldap-admin:
        image: osixia/phpldapadmin:0.7.1
        ports:
            - 6443:443
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
    gerrit:
        image: jfactory/gerrit:latest
        expose:
            - "8080"
            - "29418"
        ports:
            - "29418:29418"
        environment:
            # http
            "MAIN_URL": https://jfactory.atteo.com/gerrit/

            # auth
            "GIT_BASIC_AUTH_POLICY":

            # gitweb
            "GITWEB_TYPE":

            # ldap
            "LDAP_URL": ldap://ldap
            "LDAP_ACCOUNT_BASE": ou=people,dc=example,dc=com
            "LDAP_GROUP_BASE": ou=groups,dc=example,dc=com

            # smtp
            "SMTP_SERVER":
            "SMTP_SERVER_PORT":
            "SMTP_FROM":

            # jira
            "JIRA_URL":
        volumes:
            - gerrit:/home/gerrit/review_site
            - ./certificates/jenkins_key.pub:/home/gerrit/review_site/jenkins_key.pub
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: unless-stopped
    nexus:
        image: sonatype/nexus3
        environment:
            "NEXUS_CONTEXT": "nexus"
        expose:
            # www
            - "8081"
            # docker registry
            - "5000"
        volumes:
            - nexus:/nexus-data
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: unless-stopped
    jenkins:
        image: jfactory/jenkins:latest
        expose:
            - "8080"
        # Slaves access Jenkins on this port
        ports:
            - "50000:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - ./certificates/jenkins_key:/var/jenkins_home/jenkins_ssh_key
            # See: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
            - /var/run/docker.sock:/run/docker.sock
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            # http
            "MAIN_URL": http://jfactory.atteo.com/jenkins/
            "JENKINS_SMTP_FROM": tichy@atteo.com
        restart: unless-stopped
    proxy:
        image: jfactory/proxy:2.1
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        volumes:
            - ./certificates/nginx-server.key:/etc/nginx/certificates/server.key
            - ./certificates/nginx-server.crt:/etc/nginx/certificates/server.crt
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: unless-stopped
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.179.0.0/16

