version: '2.1'
volumes:
    slave-m2-repository:
    gerrit:
    jenkins:
    nexus:
services:
    gerrit:
        image: jfactory/gerrit:2.0
        expose:
            - "8080"
            - "29418"
        ports:
            - "29418:29418"
        environment:
            # http
            "MAIN_URL":

            # ldap
            "LDAP_URL":
            "LDAP_ACCOUNT_BASE":
            "LDAP_GROUP_BASE":

            # smtp
            "SMTP_SERVER":
            "SMTP_SERVER_PORT":
            "SMTP_FROM":

            # jira
            "JIRA_URL":
        volumes:
            - gerrit:/home/gerrit/review_site
            - ./certificates/jenkins_key.pub:/home/gerrit/review_site/jenkins_key.pub
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    nexus:
        image: sonatype/nexus3
        expose:
            # www
            - "8081"
            # docker registry
            - "5000"
        volumes:
            - nexus:/nexus-data
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    jenkins:
        image: jfactory/jenkins:2.0
        expose:
            - "8080"
        # Slaves access Jenkins on this port
        ports:
            - "50000:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - ./certificates/jenkins_key:/var/jenkins_home/jenkins_ssh_key
            # See: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
            - /var/run/docker.sock:/run/docker.sock
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            # http
            "MAIN_URL":
            "JENKINS_SMTP_FROM":
    proxy:
        image: jfactory/proxy:2.0
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        volumes:
            - ./certificates/nginx-server.key:/etc/nginx/certificates/server.key
            - ./certificates/nginx-server.crt:/etc/nginx/certificates/server.crt
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.179.0.0/16

